### ISSUE TITLE
Unable to build on Node.js v12 or v14, only v10

### ISSUE THREAD

**Issue by ltfschoen** [mstable/mStable-app#162]
**Describe the bug**

When I switch to Node.js v12.18.3 or v14.7.0, then install dependencies with `yarn`, and then run `yarn provision`, it outputs the error shown in the "To Reproduce" section below. If I use an older version v10.22.0 then `yarn provision` runs successfully.

**To Reproduce**
1. Install dependencies on macOS with:
```
brew cask install ganache
npm install truffle -g
nvm use v14.7.0
```
2. Install mStable-app
```
git clone git@github.com:mstable/mStable-app.git && cd mStable-app
yarn
yarn provision
```
3. See error

```
yarn provision  
yarn run v1.22.4
$ sh ./scripts/provision.sh
Provisioning submodules
Installing contracts
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "@nomiclabs/buidler-truffle5 > @nomiclabs/truffle-contract@4.1.15" has unmet peer dependency "web3-core-promievent@^1.2.1".
warning "@nomiclabs/buidler-truffle5 > @nomiclabs/truffle-contract@4.1.15" has unmet peer dependency "web3-eth-abi@^1.2.1".
warning "@openzeppelin/test-helpers > chai-bn@0.2.1" has unmet peer dependency "bn.js@^4.11.0".
warning " > @typescript-eslint/eslint-plugin-tslint@2.21.0" has unmet peer dependency "tslint@^5.0.0".
warning "buidler-gas-reporter > eth-gas-reporter@0.2.18-beta.4" has unmet peer dependency "@codechecks/client@^0.1.0".
warning " > chai-bn@0.2.0" has unmet peer dependency "bn.js@^4.11.0".
warning "eslint-config-airbnb-typescript > eslint-config-airbnb@18.0.1" has unmet peer dependency "eslint-plugin-react-hooks@^1.7.0".
warning "ethlint > solium-plugin-security@0.1.1" has unmet peer dependency "solium@^1.0.0".
warning "typechain > ts-essentials@6.0.4" has incorrect peer dependency "typescript@>=3.7.0".
[4/4] 🔨  Building fresh packages...
[-/24] ⡀ waiting...
[-/24] ⢀ waiting...
[-/24] ⢀ waiting...
[12/24] ⢀ scrypt
warning Error running install script for optional dependency: "/Users/ls/code/src/ltfschoen/mStable-app/lib/mStable-subgraph/lib/mStable-contracts/node_modules/scrypt: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /Users/ls/code/src/ltfschoen/mStable-app/lib/mStable-subgraph/lib/mStable-contracts/node_modules/scrypt
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@12.18.3 | darwin | x64
gyp info find Python using Python version 2.7.16 found at \"/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python\"
gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
gyp info spawn args [
gyp info spawn args   '/Users/ls/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/ls/code/src/ltfschoen/mStable-app/lib/mStable-subgraph/lib/mStable-contracts/node_modules/scrypt/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/ls/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/ls/Library/Caches/node-gyp/12.18.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/ls/Library/Caches/node-gyp/12.18.3',
gyp info spawn args   '-Dnode_gyp_dir=/Users/ls/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/ls/Library/Caches/node-gyp/12.18.3/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/ls/code/src/ltfschoen/mStable-app/lib/mStable-subgraph/lib/mStable-contracts/node_modules/scrypt',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
```

**Expected behavior**
It should build without that error, or notify the user that the error is because they are using an unsupported version of Node.js

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser N/A
 - Version 10.15.6

**Comment by ltfschoen** [comment]
If that's the case then it works and doesn't look like we need this PR https://github.com/mstable/mStable-app/pull/163

**Comment by ltfschoen** [comment]
@JamesLefrere  I think this is still an issue since Ganache is not yet supported by Node.js v14, but works with v12.

So I think we need PR #163, but with `"node": "12.x",` instead of `"node": "10.x",`.

Otherwise when users get to the step of running Ganache, if they're using the latest version of Node.js v14, then they'll encounter error:
```
Error: Callback was already called.
    at /Users/ls/.nvm/versions/node/v14.7.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:19:276
    at s.<anonymous> (/Users/ls/.nvm/versions/node/v14.7.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:19:2238)
    at s.emit (events.js:314:20)
    at s.destroy (/Users/ls/.nvm/versions/node/v14.7.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:39:744230)
    at finish (_stream_writable.js:658:14)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by JamesLefrere** [comment]
Hey @ltfschoen I'm not sure if you still need this given that it's possible to get started with the app on Ropsten now, but I did just try with node `v14.7.0` and each step worked, including migration on Ganache. The Ganache issue is here https://github.com/trufflesuite/ganache-cli/issues/732 . Perhaps my version of Ganache is outdated? (2.4.0).
