### ISSUE TITLE
Cannot query field "totalSwapVolume" on type "Pool"

### ISSUE THREAD

**Issue by gusjasponde** [mstable/mStable-app#182]
When running `yarn codegen` I get the following error:

```bash
ts-gen: 💎 All done! Generated files: 207
$ graphql-codegen --config ./codegen.yml -r dotenv/config
  ✔ Parse configuration
  ❯ Generate outputs
    ✔ Generate ./src/graphql/mstable/schema.graphql
    ✔ Generate ./src/graphql/uniswap/schema.graphql
    ✔ Generate ./src/graphql/balancer/schema.graphql
    ✔ Generate ./src/graphql/blocks/schema.graphql
    ✔ Generate ./src/graphql/mstable.tsx
    ✔ Generate ./src/graphql/uniswap.tsx
    ❯ Generate ./src/graphql/balancer.tsx
      ✔ Load GraphQL schemas
      ✔ Load GraphQL documents
      ✖ Generate
        →         at /home/gus/Projects/mstable/mStable-app/src/graphql/balancer/query.graphql:40:3
    ✔ Generate ./src/graphql/blocks.tsx
    ✔ Generate ./src/graphql/scripts.tsx


 Found 1 error

  ✖ ./src/graphql/balancer.tsx
    AggregateError: 
        GraphQLDocumentError: Cannot query field "totalSwapVolume" on type "Pool".
            at /home/gus/Projects/mstable/mStable-app/src/graphql/balancer/query.graphql:4:3
        GraphQLDocumentError: Unknown type "TokenPrice".
            at /home/gus/Projects/mstable/mStable-app/src/graphql/balancer/query.graphql:16:31
        GraphQLDocumentError: Cannot query field "tokenPrices" on type "Query".
            at /home/gus/Projects/mstable/mStable-app/src/graphql/balancer/query.graphql:34:3
        GraphQLDocumentError: Cannot query field "tokenPrice" on type "Query".
            at /home/gus/Projects/mstable/mStable-app/src/graphql/balancer/query.graphql:40:3
        at Object.checkValidationErrors (/home/gus/Projects/mstable/mStable-app/node_modules/@graphql-toolkit/common/index.cjs.js:451:15)
        at Object.codegen (/home/gus/Projects/mstable/mStable-app/node_modules/@graphql-codegen/core/index.cjs.js:99:16)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
        at async process (/home/gus/Projects/mstable/mStable-app/node_modules/@graphql-codegen/cli/bin.js:829:56)
        at async Promise.all (index 0)
        at async /home/gus/Projects/mstable/mStable-app/node_modules/@graphql-codegen/cli/bin.js:836:37
        at async Task.task (/home/gus/Projects/mstable/mStable-app/node_modules/@graphql-codegen/cli/bin.js:618:17)
    AggregateError: 
        GraphQLDocumentError: Cannot query field "totalSwapVolume" on type "Pool".
            at /home/gus/Projects/mstable/mStable-app/src/graphql/balancer/query.graphql:4:3
        GraphQLDocumentError: Unknown type "TokenPrice".
            at /home/gus/Projects/mstable/mStable-app/src/graphql/balancer/query.graphql:16:31
        GraphQLDocumentError: Cannot query field "tokenPrices" on type "Query".
            at /home/gus/Projects/mstable/mStable-app/src/graphql/balancer/query.graphql:34:3
        GraphQLDocumentError: Cannot query field "tokenPrice" on type "Query".
            at /home/gus/Projects/mstable/mStable-app/src/graphql/balancer/query.graphql:40:3
        at Object.checkValidationErrors (/home/gus/Projects/mstable/mStable-app/node_modules/@graphql-toolkit/common/index.cjs.js:451:15)
        at Object.codegen (/home/gus/Projects/mstable/mStable-app/node_modules/@graphql-codegen/core/index.cjs.js:99:16)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
        at async process (/home/gus/Projects/mstable/mStable-app/node_modules/@graphql-codegen/cli/bin.js:829:56)
        at async Promise.all (index 0)
        at async /home/gus/Projects/mstable/mStable-app/node_modules/@graphql-codegen/cli/bin.js:836:37
        at async Task.task (/home/gus/Projects/mstable/mStable-app/node_modules/@graphql-codegen/cli/bin.js:618:17)


Something went wrong
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
I've cloned the project and followed the instructions

I don't know much abount GraphQL, so I didnt go far with this issue
Thanks in advance

**Comment by JamesLefrere** [comment]
Hey @gusjasponde , thanks for bringing this to our attention. I see what the issue is; the `.env.example.ropsten` file in the readme uses the Ropsten version of Balancer's subgraph, but unfortunately that is not actively maintained, and it breaks the codegen. 

Since the Balancer subgraph is only used in EARN (which is not available on Ropsten either), I would suggest replacing this line in your `.env` file:

Change: 

```
REACT_APP_GRAPHQL_ENDPOINT_BALANCER=https://api.thegraph.com/subgraphs/name/balancer-labs/balancer-ropsten
```

to:

```
REACT_APP_GRAPHQL_ENDPOINT_BALANCER=https://api.thegraph.com/subgraphs/name/balancer-labs/balancer
```

The codegen should work fine after that :+1:
